### ISSUE TITLE
Immich restore failed on failed upgrade

### ISSUE THREAD

**Issue by MadMan247** [YunoHost-Apps/immich_ynh#127]
Looks like the upgrade issues are fixed with #126 , but I also encountered an issue with the restore/backup function that needs addressing.

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.2.31
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: Typically Behind a reverse proxy (currently not behind one)
- Using, or trying to install package version/branch: 118.2~ynh1
- If upgrading, current package version: 117~ynh2

### Steps to reproduce

attempted to update Immich via webadmin

### Expected behavior

should a install fail, a backup should be restored

### Logs

Upgrade (error) https://paste.yunohost.org/raw/awafutuzam
remove (success) https://paste.yunohost.org/raw/tunecofivu
**Restore (error)** https://paste.yunohost.org/raw/ewocevofim
remove (success) https://paste.yunohost.org/raw/ihisewocek

**Comment by ewilly** [comment]
`the restore/backup function that needs addressing.` can't see anything wrong in the both script of the app :(

**Comment by MadMan247** [comment]
I don't particularly see anything wrong myself, other than the fact that there was in fact an issue restoring immich.

Once-off issue? If so, feel free to close I guess. I did manage to restore from an older backup after all.

`2024-10-24 13:44:51,904: WARNING - Exception: Original path for "/home/yunohost.app/immich" not found` seems to be the problem line.
