### ISSUE TITLE
failed to establish 

### ISSUE THREAD

**Issue by Denizceli** [YunoHost-Apps/immich_ynh#147]
### Describe the bug

failed to establish

### Context

- Hardware: Old laptop
- YunoHost version: 12.0.8.2
- I have access to my server: Through SSH | through the webadmin 

### Steps to reproduce

   1. Go to 'apps'
   2. Click on 'install an app'
   3. Click on 'multimedia'
   4. Click on 'immich' and intall
   5. see error

### Logs
https://[paste.yunohost.org/raw/niqafawulu](https://paste.yunohost.org/raw/niqafawulu)

**Comment by ewilly** [comment]
nothing to do with immich app you have apt issues with GPG keys.
`The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E`
Please have a look at the yunohost forum to solve them.
