### ISSUE TITLE
Recommended Redis version is 6.2.0

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/immich_ynh#26]
On Immich package 1.98.2~ynh1 and YunoHost 11.2.10.3, `/var/log/immich/immich-server.log` contains the following warning:

``` 
It is highly recommended to use a minimum Redis version of 6.2.0
           Current: 6.0.16
```

**Comment by ewilly** [comment]
yes i know
redis v7 is in the backport debian repo and so could be a proper solution... 
... but redis-server is an hard dependency of yuno packages 
... so i'm not confident to update such a package and taking the risk of breaking the core function of ynh

apprently it's just a warning without visible effect on immich and as bookworn with redis v7 is coming soon i prefered to ignore that warning and wait (benefit < risk)
what's you thought ?
