### ISSUE TITLE
Machine learning misconfiguration

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/immich_ynh#30]
Upon initial installation, I noticed the face recognition was not working.

Log from `/var/log/immich/immich-microservices.log`

```
[Nest] 588565  - 04/13/2024, 10:01:05 PM   ERROR [JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with Error: getaddrinfo ENOTFOUND immich-machine-learning
```

Replacing the machine learning server setting to `http://127.0.0.1:3003` fixed the issue. What's weird is that the `env` file already has this setting set correctly, but the setting in the webapp was `http://immich-machine-learning:3003` has show by the logs.

**Comment by ewilly** [comment]
Hi,
strange because if you not force the value in webui the default value is the one in the env file.
What's the output of `sudo --login --user=postgres PGUSER=postgres PGPASSWORD="$(cat /etc/yunohost/psql)" psql --cluster="16/main" --dbname=immich --command="SELECT * FROM system_config WHERE key = 'machineLearning.url';"` ?

**Comment by tituspijean** [comment]
It's the right value, since I manually fixed it:
```
         key         |          value
---------------------+-------------------------
 machineLearning.url | "http://127.0.0.1:3003"
(1 row)
```

**Comment by ewilly** [comment]
ok and now if you delete it with `sudo --login --user=postgres PGUSER=postgres PGPASSWORD="$(cat /etc/yunohost/psql)" psql --cluster="16/main" --dbname=immich --command="DELETE FROM system_config WHERE key = 'machineLearning.url';"`
and refresh the webui what's the value in webui ?

**Comment by tituspijean** [comment]
It remains the same (`http://127.0.0.1:3003`), even after restarting the `immich-server` service. 😕

**Comment by ewilly** [comment]
hum i don't know why but on your system `http://immich-machine-learning:3003` was saved in psql settings and so take over of the value in env. By deleting that setting in psql, immich take the default one which is the one in the env file.
