### ISSUE TITLE
proper way to use nextcloud data as external library (add documentation?)

### ISSUE THREAD

**Issue by yekibud** [YunoHost-Apps/immich_ynh#38]
### Describe the bug

Missing documentation for how to add nextcloud user data as an external library.

### Context

- Hardware: 8gb 4core VPS
- YunoHost version: 11.2.11.3
- I have access to my server: ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.103.1~ynh1

### Steps to reproduce

Add a YNH nextcloud user data path, e.g. `/home/yunohost.app/nextcloud/data/username/files/Photos`.  The admin UI shows "permission denied" by default.

I understand there will probably need to be a few additional steps to support this use case, but I think some documentation explaining the proper way to do so would be very helpful for YNH users who use Nextcloud Sync for file and photo sync.  I tried adding immich to the nextcloud group, but didn't have success, so I wound up adding read access to the user data directory and corresponding umask to the nextcloud PHP process, which is probably not the right way to do it.

### Expected behavior

YNH nextcloud data as external library is properly mounted and can be sync'd/imported.

**Comment by ewilly** [comment]
Making such a possibility is creating a security issue against nextcloud. Can't do that.

**Comment by yekibud** [comment]
@ewilly I'm not sure you understood my suggestion.  I'm saying that the way I have integrated nextcloud is _not_ the proper way.  Are you saying there is _no_ proper way to use nextcloud sync for photo file management and an external library for immich?

**Comment by ewilly** [comment]
The only proper way i see is using the ynh multimedia share folder which is already possible with nextcloud and will be possible with immich in the next version.

**Comment by yekibud** [comment]
> The only proper way i see is using the ynh multimedia share folder which is already possible with nextcloud and will be possible with immich in the next version.

@ewilly do you know what immich version and feature would support the multimedia share folder?  I didn't see it in the immich github repo looking for keywords "multimedia", "nextcloud", etc.
