### ISSUE TITLE
Big files can't be uploaded because of `client_max_body_size` in nginx config

### ISSUE THREAD

**Issue by lyynd** [YunoHost-Apps/immich_ynh#53]
### Describe the bug

Videos bigger that ~500MiB can't be uploaded.

### Context

- Hardware: mini PC with an AMD CPU.
- YunoHost version: 11.2.14.1
- I have access to my server: Through SSH.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no.
- Using, or trying to install package version/branch: 1.106.4~ynh1

### Steps to reproduce

Have any video larger than 500MiB on a mobile device and try to upload it.

### Expected behavior

Video is uploaded.

### Logs

in `/var/log/nginx/REDACTED-error.log`:

```2024/06/12 22:03:46 [error] 302167#302167: *2957 client intended to send too large chunked body: REDACTED bytes, client: REDACTED, server: REDACTED, request: "POST /api/asset/upload HTTP/1.1", host: "REDACTED"```

in `/var/log/nginx/REDACTED-access.log`:

```REDACTED - - [12/Jun/2024:22:04:16 +0000] "POST /api/asset/upload HTTP/1.1" 413 176 "-" "Dart/3.3 (dart:io)"```

### Fix

Raising `client_max_body_size` in `conf/nginx.conf` should help, but choosing the right limit is challenging. I had videos as big as 10s of GiB. I think that the best solution here is to have the limit as a config option, maybe even show the option on install page, and prominently notify about it's existence, because right now the client does not show any kind of error and tries to re-upload repeatedly.

**Comment by ewilly** [comment]
Thanks for pointing that issue !
Normally fix with https://github.com/YunoHost-Apps/immich_ynh/pull/54/commits/4c279878217e05a4f75cac9d8cbfac2cc821043f
Can you test and come back to me ?
`sudo yunohost app upgrade immich -u https://github.com/YunoHost-Apps/immich_ynh/tree/testing --force`

**Comment by lyynd** [comment]
Thanks. This should work for now. I just wonder what would one do if a video is bigger than 50GiB (which can happen especially when filming in 4K). Unfortunately there is no way to persistently change nginx conf in yunohost.

**Comment by ewilly** [comment]
In that case, i'm not sure that immich is the best solution.  Immich is more focused on photos and videos management, not films.
