### ISSUE TITLE
Videos are broken in the web view

### ISSUE THREAD

**Issue by lyynd** [YunoHost-Apps/immich_ynh#70]
### Describe the bug

Videos in the web view are broken (show a broken thumbnail icon, the same when clicking the video) because of issues with transcoding.

### Context

- Hardware: Mini PC
- YunoHost version: 11.2.24
- I have access to my server: ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.109.2~ynh2

### Steps to reproduce

Upload a video. I guess it's important that Immich tries to transcode it, although disabling transcoding does not fix the issue.

### Expected behavior

The video with thumbnail and preview is shown.

### Logs

```
[Nest] 175  - 07/25/2024, 12:02:15 AM   ERROR [Microservices:MediaRepository] ffmpeg version 4.3.7-0+deb11u1 Copyright (c) 2000-2024 the FFmpeg developers                              
Error splitting the argument list: Option not found                                         
[Nest] 175  - 07/25/2024, 12:02:15 AM   ERROR [Microservices:JobService] Unable to run job handler(thumbnailGeneration/generate-preview): Error: ffmpeg exited with code 1: Unrecognized option 'fps_mode'.  
```

### My ideas and a fix

Upstream Immich Docker images use latest releases of jellyfin-ffmpeg (ffmpeg version 6.0.1-Jellyfin) by manually downloading the deb files from Jellyfin's site. See a similar bug report here:
https://forum.cloudron.io/topic/9785/error-mediaservice-error-ffmpeg-exited-with-code-1-unrecognized-option-fps_mode
Right now it's done in the base image:
https://github.com/immich-app/base-images/blob/fb59996c50d670b2d765f0b8f85b6709f81bf6c4/server/bin/install-ffmpeg.sh
I installed jellyfin-ffmpeg manually and symlinked it to ```/usr/local/bin/``` and it fixed the issue after rerunning transcoding. I guess a similar thing can be done on install in yunohost, but symlinking is prone to conflicts (e.g. if another app would like to do the same), so patching Immich to change ffmpeg usage to an absolute path might be an option. Or maybe we could ask upstream Immich to add an option of specifying a path to ffmpeg (but this would take time).

**Comment by ewilly** [comment]
Thanks for the issue, the tests and the idea :-)
Normally solved with https://github.com/YunoHost-Apps/immich_ynh/pull/73/commits/006dd16141e558c5830a342397d6c2475ee3c49d
