### ISSUE TITLE
Immich Upgrade to latest version failed

### ISSUE THREAD

**Issue by mikerjensen** [YunoHost-Apps/immich_ynh#77]
I have been upgrading Immich (along with all OS and yunohost upgrades) successfully through each new version until today when i tried to upgrade to the current version (from 1.110.0~ynh1 to 1.110.0~ynh2 ) which  'failed to roll-back'.  as per the below error summary.
Please see the link for further details:
https://paste.yunohost.org/raw/sexumehuje

Error: "500"

Action: "PUT" /yunohost/api/apps/immich/upgrade

Error message:
Could not complete the operation 'Upgrade the 'immich' app'. Please provide the full log of this operation by [clicking here](https://192.168.86.43/yunohost/admin/#/tools/logs/20240730-133858-app_upgrade-immich) to get help

While processing the action the server said:
Now upgrading immich…
Creating a safety backup prior to the upgrade
Collecting files to be backed up for immich…
Declaring files to be backed up...
/home/yunohost.app/immich will not be saved, because 'BACKUP_CORE_ONLY' is set.
Backing up a PostgreSQL database...
Backup script completed for immich. (YunoHost will then actually copy those files to the archive).
Creating a backup archive from the collected files…
The archive will contain about 2.2GB of data.
Backup created: immich-pre-upgrade1
Backup deleted: immich-pre-upgrade2
Updating sources...
Updating ports...
Updating system_user...
Updating install_dir...
Updating data_dir...
Failed to update data_dir : [Errno 17] File exists: '/home/yunohost.app/immich'
Reverting sources...
Reverting ports...
Reverting system_user...
Reverting install_dir...
Reverting data_dir...
Failed to rollback data_dir : [Errno 17] File exists: '/home/yunohost.app/immich'
Provisioning, deprovisioning, or updating resources for immich failed: [Errno 17] File exists: '/home/yunohost.app/immich'

**Comment by ewilly** [comment]
Start by updating yunohost to 11.2.25 and then immich.
If it's still failling wat is the output of those 2 commands :
`cat /etc/yunohost/apps/immich/settings.yml | grep data_dir`
`ls -ali /home/yunohost.app/immich`
?

**Comment by mikerjensen** [comment]
Thanks for the advice, upgrading to 11.2.25 seems to have worked,
      no errors reported on the Immich upgrade.
    On 7/31/24 07:17, ewilly wrote:
    
    
      
      Start by updating yunohost to 11.2.25 and then
        immich.
        If it's still failling wat is the output of those 2 commands :
        cat
          /etc/yunohost/apps/immich/settings.yml | grep data_dir
        ls -ali /home/yunohost.app/immich
        ?
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/YunoHost-Apps/immich_ynh/issues/77#issuecomment-2259753377",
"url": "https://github.com/YunoHost-Apps/immich_ynh/issues/77#issuecomment-2259753377",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
