### ISSUE TITLE
installation error: ffmpeg-static checksum error

### ISSUE THREAD

**Issue by mc-knife** [YunoHost-Apps/immich_ynh#83]
### Describe the bug

Installation error
### Context

- Hardware: Dell Wyse 5010 D10D (8GB) at home
- YunoHost version: 11.2.27
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version1.112.1~ynh1

### Steps to reproduce

-click "install" or
-cli: `sudo yunohost app install https://github.com/YunoHost-Apps/immich_ynh --debug`

--> error:
`ERROR - Automatische Ressourcen-Allokation (provisioning), die Unterbindung des Zugriffts auf Ressourcen (deprovisioning) oder die Aktualisierung der Ressourcen für immich schlug fehl: YunoHost konnte die Ressource 'ffmpeg-static' (https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz) für immich herunterladen, aber die Ressource stimmt mit der erwarteten Checksum nicht überein.`

### Expected behavior

-click "install"
-installs
### Logs
https://paste.yunohost.org/raw/qohiqiqeho

**Comment by Paradroyd** [comment]
I tried to update via the shell as I always do and had the same issue.

Log is here...
[https://paste.yunohost.org/raw/puxacirizo](https://paste.yunohost.org/raw/puxacirizo)

**Comment by mc-knife** [comment]
quick update, after yunohost update to 11.2.28 (and other updates): 
immich install is running and working beyound _this_ error... 
(thanks for the quick reaktions. i will keep you updated).

**Comment by ewilly** [comment]
Solved with #84
