### ISSUE TITLE
error in installation script

### ISSUE THREAD

**Issue by mc-knife** [YunoHost-Apps/immich_ynh#85]
### Describe the bug

Installation error
### Context

- Hardware: Dell Wyse 5010 D10D (8GB) at home
- YunoHost version: 11.2.28
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version1.112.1~ynh1

### Steps to reproduce

-click "install"
--> `2024-08-27 12:35:15,854: ERROR - Installation von immich fehlgeschlagen: Im Installationsscript ist ein Fehler aufgetreten
`
### Expected behavior

-click "install"
-installs
### Logs
https://paste.yunohost.org/raw/rarigucezo

**Comment by ewilly** [comment]
Wait for 1.112.1~ynh2

**Comment by mc-knife** [comment]
[log](https://paste.yunohost.org/raw/rarigucezo) shows: error resulted in trying 1.112.1~ynh2
(my mistake in issue description: copy&pasted the old version; fixed!)
